### ISSUE TITLE
Consistent wording in messages

### ISSUE THREAD

**Issue by ccoffrin** [aayushGaur/stac#12]
The warning and error messages would be improved by more consistent wording.

Case 1) All of the constraint bound violations should read "<variable name> is out of bounds."

This applies to,
- p,q on generators
- v on buses
- angle differences on lines

Case 2) Messages involving thermal limits should be along the lines of "Rate A thermal limit violated."  Warnings about the implied upper bound could be made to be similar to this.  For example, "Rate A thermal limit is larger than the implied upper bound (<value> MVA)."

**Comment by aayushGaur** [comment]
Made required changes in the feedback text.
