### ISSUE TITLE
Linear Generator Cost Functions

### ISSUE THREAD

**Issue by ccoffrin** [aayushGaur/stac#13]
Currently the tool throws an error "The format of the Input file is not correct." when a linear cost function is entered.  

It seems since version 5.0 a number of the new Matpower cases have such cost functions (e.g. see case5.m), so we should add this to the parser's capabilities.

Reported by Alberto Lamadrid

**Comment by aayushGaur** [comment]
Updated the parser to support Linear Generator Cost functions.
