### ISSUE TITLE
Recovering from unexpected Generator Costs

### ISSUE THREAD

**Issue by ccoffrin** [aayushGaur/stac#15]
The tool seems to have recurring challenges around the generator cost function block.  Indeed, this is the most complex data structure in the file format.

I propose that we change the parser so that when the generator data can not be understood a warning is raised and the visualization continues, with "unknown" for the cost values.  

It would be good if the tool also worked when there was no generator cost function.  In the worst case a user can delete the cost function and then load their network.

Reported by Barry Rawn

**Comment by aayushGaur** [comment]
Updated STAC to handle the input file which do not have any generator data.
Also the previous custom error messages have not been updated/modified. They are as follows:

Case 1 - When the length of the cost data and the generator data is not equal.
Alert Message - Warning: this test case has cost values on reactive power generation that are not displayed by this tool.

Case 2 - If the value in the first column of the generator cost data the value is 1.
Alert Message - Warning: the piecewise linear generator cost functions in this test case are not displayed by this tool."

Please advise on the above two alert messages.

**Comment by aayushGaur** [comment]
Updated the rules to allow the parser to continue if the generator cost data object is missing. For this to work the whole mpc.gencost data object needs to be removed.
