### ISSUE TITLE
Missing Lines

### ISSUE THREAD

**Issue by ccoffrin** [aayushGaur/stac#17]
In some networks lines are not rendered.  The case240.m is a small example that exhibits this behavior.  It also occurs in NESTA cases with over 1000 lines.

**Comment by aayushGaur** [comment]
Unable to replicate the issue now. Validated with case240.m file.
Probably fixed with some other update.
Please verify once at your end.

**Comment by ccoffrin** [comment]
I checked on my end all lines in case240 appear to be visible.  Looks good.
