### ISSUE TITLE
Fix location of subset of buses

### ISSUE THREAD

**Issue by AliHeggie** [aayushGaur/stac#19]
Requested enhancement: Option to fix the position of some buses, and have the others adjust their position around them.

**Comment by aayushGaur** [comment]
Thanks for the suggested update. I will add this feature and make other pending updates and bug fixes after about 3 weeks (once my end semester exams are over).
Please do post any other update/ bug fix that you feel should be made in STAC.

**Comment by aayushGaur** [comment]
Updated.
Double clicking on a node (or the label inside the node) will fix/unfix its position.
A node that has been fixed will have a fill color of light blue.

**Comment by AliHeggie** [comment]
Thanks!
