### ISSUE TITLE
Comment Lines in Data Files

### ISSUE THREAD

**Issue by ccoffrin** [aayushGaur/stac#20]
If a line begins with "%" in the date file, it should be ignored by the parser.  Even if the comment line appears inside of a matrix definition.

**Comment by aayushGaur** [comment]
Updated the parser to not consider a line if it begins with '%' (in the data matrix for the various network objects).

Cases which the current changes in the parser will not be able to handle when the information regarding a bus is commented :
1. The bus is being used in some branch definition.
2. The generator information regarding the bus is still present in the file.
3. The bus location regarding the bus is still present.

All the above cases create an anomaly in the file. Support for the above will be added if such cases are encountered.

Closing for review.

**Comment by ccoffrin** [comment]
I tested the file which inspired this bug and it still does not parse.  I will send it to you for testing.

**Comment by aayushGaur** [comment]
The following updates have been made in the parser:
1. The parser will not consider any line whose first character is '%' (after the data in the line has been trimmed for white spaces).
2. As the name of attributes/properties for the elements are now being read from the rules, the parser will ignore any extra content/value for an element which exceeds the property count i.e. any content after the ';' will be ignored.
