### ISSUE TITLE
Spacing of 4 parallel lines

### ISSUE THREAD

**Issue by ccoffrin** [aayushGaur/stac#21]
There appears to be a spacing issue when 4 lines are in parallel.

For example look the transformers between buses 2612 and 2618 in case240.m

**Comment by aayushGaur** [comment]
Updated the Multiple Line Edge UI for spacing issue for 4 lines in parallel.

**Comment by ccoffrin** [comment]
The most recent fix seems to have created an issue for double lines, which are much more prevalent than quad lines.

**Comment by aayushGaur** [comment]
Updated the Multiple Line Edge file for the regression issue.
