### ISSUE TITLE
Buses are not connected as per MATPOWER casefile

### ISSUE THREAD

**Issue by aakanksha512** [aayushGaur/stac#25]
When I load my MATPOWER case, the buses are not connected to each other as per branch connections in the case. Please let me know if there is any specific format for data input in stac.

**Comment by ccoffrin** [comment]
Can you give a specific example that is not working?  I just tried some cases from https://github.com/power-grid-lib/pglib-opf and it seemed to be working fine.

**Comment by aakanksha512** [comment]
Hi, Attached is the matpower file I am working on. When I upload the file on stac...it just plots the buses and does not connect the branches. I think it is something to do with the format of data. 
[Transmission.txt](https://github.com/aayushGaur/stac/files/1737776/Transmission.txt)

**Comment by ccoffrin** [comment]
This file uses a combination of spaces and tabs for defining the matrices.  Try making these consistent.

**Comment by aakanksha512** [comment]
Ok thanks, I will correct and get back to if it works.

**Comment by ccoffrin** [comment]
From inspecting the javascript console, it is clear that there is some issue in parsing the branch table.  The other tables appear to be fine.

**Comment by aakanksha512** [comment]
Hi, I tried to make the tables consistent, but now it says 'Unable to parse the input file.' I have attached the file for your reference. Please let me know what other changes I need to do in the matpower file. 
[Transmission1.txt](https://github.com/aayushGaur/stac/files/1738011/Transmission1.txt)

**Comment by ccoffrin** [comment]
In the branch list there was one row with a double indent, which broke the parser.  This looks like it should work.  btw, the transformer tap ratios look a bit weird.
[Transmission2.txt](https://github.com/aayushGaur/stac/files/1738148/Transmission2.txt)

**Comment by aakanksha512** [comment]
Hi Carleton, Thanks for reviewing my code. I am able to plot it on stac. For the transformer tap-ratio, I used the conversion of voltages in the transformers i.e. if a substation A is at 500kV and substation B is at 230kV, so tap ratio for the branch connecting A to B I have taken as 500/230. Also, when I input the file into stac, almost all the branches give errors 'charge is very different from x' and 'Charge value greater than 0 for transformers'. Can you help me as to what these errors mean and how can I improve my model? Thanks!

**Comment by ccoffrin** [comment]
Great to hear your case is now working.  I am going to close this issue.  For your question regarding network parameters, that is best sent to the [PowerGlobe mailing list](http://www.ece.mtu.edu/faculty/ljbohman/peec/globe/).
