### ISSUE TITLE
0 rate value in lines

### ISSUE THREAD

**Issue by ccoffrin** [aayushGaur/stac#3]
In version 5.0+ of Matpower a rating value of 0 indicates no thermal limit.  STAC currently generates a warning for this case.

Hence, when a line rating is 0 in the input, it should not generate a warning and it should display as a value of "none" in the tool tip.

See case14_rate_0.m for an example.

Reported by Ray Zimmerman.

**Comment by aayushGaur** [comment]
Made the following changes:
1. Commented the code responsible for adding the warning message for the validation on rating.
2. Added a custom attribute to display the tool-tip for the rating value.

**Comment by ccoffrin** [comment]
This is what I am currently seeing with the case14_rate_0.m

In this case the "none" should appear in all three, Rate A, Rate B, and Rate C.

The message also appears to be incorrect, it says thermal limit "and angle difference bound" violated.  The angle difference bound is also not violated in this case.

Note that a value of "0" is really a special case, which turns off the rate check.  If the value is negative is should produce an error, if the value is greater than 0 it should check the rate value.

![screen shot 2015-04-11 at 11 33 12 am](https://cloud.githubusercontent.com/assets/1105578/7099725/9fad3528-e03e-11e4-893b-984bc83c35ae.png)

**Comment by aayushGaur** [comment]
Updated the code to not perform the following validations when the value of rateA is zero:
1. Thermal rating is greater than the implied upper bound.
2. Thermal limit and angle difference bound violated.

**Comment by ccoffrin** [comment]
This change appears to be working on the case14_rate_0.m

On the other cases, which have thermal limits, only Rate A appears to be showing now, and not B and C?

Also regarding point 2.  Why is the text Thermal limit and angle difference bound?  Thermal limits and phase angle differences are two separate constraints, and should be tested separately as well.

**Comment by aayushGaur** [comment]
Made a minor bug fix for the Rate B and Rate C values.

For point 2 - 
The validation on Thermal limit and angle difference bound is being done by comparing the value of the power 's-s-t' or 's-t-s' with Rate A and an error is logged if either of the two is greater than Rate A.

**Comment by ccoffrin** [comment]
Ok, maybe the text is misleading then.  There should be two independent checks,

Check 1) if s-s-t is greater than Rate A or s-t-s is greater than Rate A (the reverse side), then an error should be generated with the message "Rate A thermal limit limit violated".

Check 2) if theta_from_bus - theta_to_bus is smaller than min_angle_difference or greater than max_angle_difference, then an error should be generated with the message "Angle difference bound violated".

**Comment by aayushGaur** [comment]
Separated the validation for Rate A thermal limit and angle difference bounds.
Please advise if the following are correct (in the current implementation):
- As per current implementation the Angle difference bound violation will be validated, irrespective of the value of Rate A i.e. even if Rate A is zero.
- The comparison is done using the 'angle' attribute present in the branch data. (this is a doubt - because using this attribute we decide whether a line is a transformer or not)

**Comment by ccoffrin** [comment]
This appears to be fixed in SHA: 315cc80964ec0af6944902bc1c71cdef6d3e341a
