### ISSUE TITLE
Input data files with PWL cost functions

### ISSUE THREAD

**Issue by ccoffrin** [aayushGaur/stac#6]
The current implementation only supports quadratic cost functions in the mpc.gencost matrix, not PWL cost functions.

When reading mpc.gencost matrix it should check that the first value of each line is "2".  If not, then it should print a warning that the cost data is being ignored.  Cost 1, Cost 2, and Cost 3 on the generators should appear as something like "NA" or a dash "-".

see case30pwl.m for an example.

Reported by Ray Zimmerman.

**Comment by aayushGaur** [comment]
Added the required validation while adding the Generator Cost data.
Also updated the logic for adding the warning for Generator Cost data.
- Added the same validation for Synchronous Condenser also.

**Comment by ccoffrin** [comment]
The change to the cost value in the tool tip looks good.

Per the Matpower format, this will be a global property on all of the generators.  They will all be type 1 (PWL) or all be type 2 (polynomial).  Hence, I think it's best to simply make a general warning when the file is first loaded, via a dialog box.  After that no more warnings are needed.

The warning would read along the lines of "Warning: the piecewise linear generator cost functions in this test case are not displayed by this tool."

**Comment by aayushGaur** [comment]
Updated to show the warning message to user when the test case is loaded.
