### ISSUE TITLE
Privacy and Useability Notes

### ISSUE THREAD

**Issue by ccoffrin** [aayushGaur/stac#8]
At the bottom of the landing page the following text should be added in a small unobtrusive style.  

"This is a client-side visualization tool.  Case files displayed by the tool remain in local memory.  

Viewing networks with less than 500 buses is recommended for the best user experience."

Reported by Ray Zimmerman.

**Comment by aayushGaur** [comment]
Added the text to the landing page.

**Comment by ccoffrin** [comment]
I made some minor changes to the style of this note and committed the changes.
