### ISSUE TITLE
Thermal Limit Violations for Rate B and Rate C

### ISSUE THREAD

**Issue by ccoffrin** [aayushGaur/stac#9]
Add thermal limit violation errors for Rate B and C, along the lines of Rate A.

**Comment by aayushGaur** [comment]
Added a validation to check if the values of RateB and RateC are less than zero.
The error message is  - Rate B (Thermal Limit) is Negative.

Also the following check has been included in the validation - 
((((data.edgeData.angmax - data.edgeData.angmin) \* Math.PI)/180) > 
(2 \* Math.max(Math.abs(data.source.Vmax - data.target.Vmin), Math.abs(data.source.Vmin - data.target.Vmax)))) 

Please advise if these need to be updated.
